-- DATABASE: mindlytools
CREATE DATABASE IF NOT EXISTS mindlytools;
USE mindlytools;

-- TABLE: users

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  uid VARCHAR(255) UNIQUE NOT NULL,             -- Firebase UID
  email VARCHAR(255) NOT NULL,
  username VARCHAR(255) UNIQUE,                 -- User-chosen username
  name VARCHAR(255),                            -- From Google profile
  picture VARCHAR(255),                         -- Google photo URL
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


-- TABLE: todos

CREATE TABLE IF NOT EXISTS todos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  done TINYINT(1) DEFAULT 0,
  userId INT,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  CONSTRAINT fk_todos_user
    FOREIGN KEY (userId) REFERENCES users(id)
    ON DELETE CASCADE
);

-- TABLE: notes

CREATE TABLE IF NOT EXISTS notes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  content TEXT NOT NULL,
  userId INT,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  CONSTRAINT fk_notes_user
    FOREIGN KEY (userId) REFERENCES users(id)
    ON DELETE CASCADE
);

-- TABLE: toolusages

CREATE TABLE IF NOT EXISTS toolusages (
  id INT AUTO_INCREMENT PRIMARY KEY,
  toolName VARCHAR(255),
  userId INT,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  CONSTRAINT fk_toolusage_user
    FOREIGN KEY (userId) REFERENCES users(id)
    ON DELETE CASCADE
);
